#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" || return ; pwd -P )"

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

pkill compton
pkill picom
pkill polybar
pkill blueman-applet
pkill nm-applet
#pkill dunst
