#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH/down" /tmp/leftwm-theme-down

# Boot picom (compositor)
picom --config "$SCRIPTPATH/picom/picom.conf" &> /dev/null &

# Load the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > "$XDG_RUNTIME_DIR/leftwm/commands.pipe"

# Load background
feh --no-fehbg --bg-fill "$SCRIPTPATH/Backgrounds/0143.jpg"
# Start networkManager applet
nm-applet &
blueman-applet &

# Start polybar
pkill polybar
export index=0
monitors="$(polybar -m | sed s/:.*// | tac)"
while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar --reload &> /dev/null &
    let index = index+1
done <<< "$monitors"
exit 0

# Todo
# dunst run and config
