#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH/down" /tmp/leftwm-theme-down

# Boot picom (compositor)
picom --config "$SCRIPTPATH/picom/picom.conf" &> /dev/null &

# Load the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Load background
feh --no-fehbg --bg-fill "$SCRIPTPATH/Backgrounds/0143.jpg"

# Start applets
nm-applet &
blueman-applet &

# Start polybar
pkill polybar
index=0
monitors=$(polybar -m | awk -F ':' '{ printf $1"\n" }')
while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar$index --reload &> /dev/null &
    let index=index+1
done <<< "$monitors"
exit 0

# Todo
# dunst run and config
